name: image_video_picker_example

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # pick video & image
  image_picker: ^0.6.7+11

  # play video
  video_player: ^0.10.12+4

  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
